default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres

development:
  <<: *default
  database: raidbuddy_development

test:
  <<: *default
  database: raidbuddy_test

production:
  <<: *default
  database: raidbuddy_production
  username: raidbuddy
  password: <%= ENV['RAIDBUDDY_DATABASE_PASSWORD'] %>
